# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './src/gedagui/resources/mainWindow.ui'
#
# Created by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.path_lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.path_lineEdit.setObjectName(_fromUtf8("path_lineEdit"))
        self.horizontalLayout.addWidget(self.path_lineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(250, 250))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.selected_listWidget = QtGui.QListWidget(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selected_listWidget.sizePolicy().hasHeightForWidth())
        self.selected_listWidget.setSizePolicy(sizePolicy)
        self.selected_listWidget.setMaximumSize(QtCore.QSize(300, 16777215))
        self.selected_listWidget.setDragEnabled(True)
        self.selected_listWidget.setDragDropMode(QtGui.QAbstractItemView.DropOnly)
        self.selected_listWidget.setDefaultDropAction(QtCore.Qt.CopyAction)
        self.selected_listWidget.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.selected_listWidget.setObjectName(_fromUtf8("selected_listWidget"))
        self.verticalLayout_3.addWidget(self.selected_listWidget)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.file_treeView = QtGui.QTreeView(self.centralwidget)
        self.file_treeView.setDragEnabled(True)
        self.file_treeView.setDragDropMode(QtGui.QAbstractItemView.DragOnly)
        self.file_treeView.setAlternatingRowColors(True)
        self.file_treeView.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.file_treeView.setSelectionBehavior(QtGui.QAbstractItemView.SelectItems)
        self.file_treeView.setAutoExpandDelay(1)
        self.file_treeView.setSortingEnabled(True)
        self.file_treeView.setAnimated(False)
        self.file_treeView.setObjectName(_fromUtf8("file_treeView"))
        self.verticalLayout.addWidget(self.file_treeView)
        self.buttonBox = QtGui.QDialogButtonBox(self.centralwidget)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuSettings = QtGui.QMenu(self.menubar)
        self.menuSettings.setObjectName(_fromUtf8("menuSettings"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuLocations = QtGui.QMenu(self.menubar)
        self.menuLocations.setObjectName(_fromUtf8("menuLocations"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setMaximumSize(QtCore.QSize(16777215, 100))
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionQuit = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/system-shutdown.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuit.setIcon(icon)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionAbout = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/gtk-info.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon1)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionOpen_location = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/document-open.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen_location.setIcon(icon2)
        self.actionOpen_location.setObjectName(_fromUtf8("actionOpen_location"))
        self.actionAdd_bookmark = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/list-add.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAdd_bookmark.setIcon(icon3)
        self.actionAdd_bookmark.setObjectName(_fromUtf8("actionAdd_bookmark"))
        self.actionDelete_bookmark = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/list-remove.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDelete_bookmark.setIcon(icon4)
        self.actionDelete_bookmark.setObjectName(_fromUtf8("actionDelete_bookmark"))
        self.actionPreferences = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/control-center2.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPreferences.setIcon(icon5)
        self.actionPreferences.setObjectName(_fromUtf8("actionPreferences"))
        self.menuFile.addAction(self.actionOpen_location)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuSettings.addAction(self.actionPreferences)
        self.menuHelp.addAction(self.actionAbout)
        self.menuLocations.addAction(self.actionAdd_bookmark)
        self.menuLocations.addAction(self.actionDelete_bookmark)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuLocations.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionOpen_location)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionQuit)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.actionQuit, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "gedaGUI", None))
        self.label.setText(_translate("MainWindow", "Path", None))
        self.groupBox.setTitle(_translate("MainWindow", "Selected zips", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.menuLocations.setTitle(_translate("MainWindow", "Bookmarks", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.actionQuit.setText(_translate("MainWindow", "&Quit", None))
        self.actionAbout.setText(_translate("MainWindow", "&About", None))
        self.actionOpen_location.setText(_translate("MainWindow", "Open location", None))
        self.actionAdd_bookmark.setText(_translate("MainWindow", "Add bookmark", None))
        self.actionDelete_bookmark.setText(_translate("MainWindow", "Delete bookmark", None))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences", None))

import gedagui_rc
